//! Self-dev customization records (#42).
//!
//! When the self-dev agent (or a user manually) modifies jcode source,
//! capture a structured record of the change in `~/.jcode/customizations/`.
//! Foundation for #43 (intent + provenance + rationale) and #44 (update
//! flow integration).
//!
//! ## Schema
//!
//! Each record is one JSON file at
//! `~/.jcode/customizations/<id>.json`:
//!
//! ```json
//! {
//!   "schema_version": 1,
//!   "id": "cust_<unix_ts>_<short_hash>",
//!   "timestamp_unix": 1779504807,
//!   "timestamp_iso": "2026-05-23T18:15:00Z",
//!   "files": ["src/foo.rs"],
//!   "diff_hash": "sha256:abc123...",
//!   "intent": "human-readable reason",
//!   "session_id": "sess_xyz_abc",
//!   "version_at_record": "v0.12.97-dev",
//!   "git_hash_at_record": "65e18d9b"
//! }
//! ```
//!
//! `schema_version: 1` is the current contract; readers should accept any
//! version they were built against. Future fields (provenance #43,
//! validation #43, status #44) are additive.

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};

/// Current schema version. Bump when introducing breaking changes.
pub const SCHEMA_VERSION: u32 = 1;

/// One customization event.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomizationRecord {
    /// Schema version this record was written against.
    #[serde(default = "default_schema_version")]
    pub schema_version: u32,

    /// Stable identifier of the form `cust_<unix_ts>_<short_hash>`.
    pub id: String,

    /// Unix epoch seconds when the record was created.
    pub timestamp_unix: u64,

    /// ISO-8601 timestamp (UTC) when the record was created.
    pub timestamp_iso: String,

    /// Files touched by this customization (relative to repo root or
    /// absolute, caller's choice; we don't normalize here).
    pub files: Vec<String>,

    /// SHA-256 hash of the unified diff for this customization. Lets the
    /// update-flow integration (#44) detect whether the customization
    /// still applies cleanly to a new release.
    pub diff_hash: String,

    /// Human-readable reason. May be agent-generated or user-typed.
    pub intent: String,

    /// jcode session id this customization originated from, when known.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,

    /// jcode version at record time (e.g. `v0.12.97-dev`).
    pub version_at_record: String,

    /// Git hash at record time.
    pub git_hash_at_record: String,

    // ---- #43: provenance + rationale + validation ----
    /// Who or what initiated the customization. `None` for legacy v1
    /// records (forward-compat).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub provenance: Option<Provenance>,

    /// The agent's reasoning trace when the change was generated by
    /// self-dev. For user-driven customizations this is typically `None`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rationale: Option<String>,

    /// Validation evidence captured before the customization was applied.
    /// Used by `jcode update` (#44) to decide whether a customization
    /// still passes against a new release.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub validation: Option<Validation>,
}

/// Where this customization came from.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Provenance {
    /// User typed the change directly via editor.
    User { author: Option<String> },
    /// Self-dev agent produced the change.
    SelfDev {
        /// Provider+model that generated the patch (e.g. "anthropic/claude-sonnet-4").
        agent: String,
        /// Optional task / prompt id that drove the generation.
        task_id: Option<String>,
    },
    /// Imported from an external source (e.g. a git apply, package install).
    External { source: String },
}

/// Validation evidence — what was tested + the outcome.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Validation {
    /// Free-form description of what was checked
    /// (e.g. "cargo test -p jcode --lib customization::tests").
    pub description: String,
    /// True if validation passed at record time.
    pub passed: bool,
    /// Optional structured detail — output excerpts, test names, etc.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
}

fn default_schema_version() -> u32 {
    1
}

fn customizations_dir() -> Result<PathBuf> {
    Ok(crate::storage::next_code_dir()?.join("customizations"))
}

/// Compute the canonical id for a record. Derives a short stable hash from
/// the unified diff so the same customization recorded twice yields the
/// same id (useful for dedup in the update flow).
fn compute_id(timestamp_unix: u64, diff_hash: &str) -> String {
    // diff_hash is already a sha256 — just take its first 12 hex chars.
    let short = diff_hash
        .strip_prefix("sha256:")
        .unwrap_or(diff_hash)
        .chars()
        .take(12)
        .collect::<String>();
    format!("cust_{timestamp_unix}_{short}")
}

/// Hash a unified diff string into `sha256:<64-hex>`.
pub fn hash_diff(diff: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(diff.as_bytes());
    let bytes = hasher.finalize();
    let mut hex = String::with_capacity(7 + 64);
    hex.push_str("sha256:");
    for byte in bytes {
        use std::fmt::Write;
        let _ = write!(hex, "{:02x}", byte);
    }
    hex
}

/// Record a new customization. Writes the JSON file under
/// `~/.jcode/customizations/<id>.json` and returns the assigned id.
pub fn record(
    intent: impl Into<String>,
    files: Vec<String>,
    diff: &str,
    session_id: Option<&str>,
) -> Result<String> {
    record_full(
        intent, files, diff, session_id, None, // provenance
        None, // rationale
        None, // validation
    )
}

/// Record a customization with all v2 fields (#43). Backwards-compatible:
/// each new field is `Option`. Use `record()` for the simpler v1
/// signature when provenance/rationale/validation aren't available.
pub fn record_full(
    intent: impl Into<String>,
    files: Vec<String>,
    diff: &str,
    session_id: Option<&str>,
    provenance: Option<Provenance>,
    rationale: Option<String>,
    validation: Option<Validation>,
) -> Result<String> {
    let dir = customizations_dir()?;
    std::fs::create_dir_all(&dir).with_context(|| format!("create {}", dir.display()))?;

    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    let diff_hash = hash_diff(diff);
    let id = compute_id(now, &diff_hash);

    let record = CustomizationRecord {
        schema_version: SCHEMA_VERSION,
        id: id.clone(),
        timestamp_unix: now,
        timestamp_iso: chrono::Utc::now().to_rfc3339(),
        files,
        diff_hash,
        intent: intent.into(),
        session_id: session_id.map(ToOwned::to_owned),
        version_at_record: next_code_build_meta::VERSION.to_string(),
        git_hash_at_record: next_code_build_meta::GIT_HASH.to_string(),
        provenance,
        rationale,
        validation,
    };

    let path = dir.join(format!("{id}.json"));
    let body = serde_json::to_string_pretty(&record).context("serialize CustomizationRecord")?;
    std::fs::write(&path, body).with_context(|| format!("write {}", path.display()))?;
    Ok(id)
}

/// Load a single record by id. Returns `Ok(None)` if not found.
pub fn get(id: &str) -> Result<Option<CustomizationRecord>> {
    let dir = customizations_dir()?;
    let path = dir.join(format!("{id}.json"));
    if !path.exists() {
        return Ok(None);
    }
    let body =
        std::fs::read_to_string(&path).with_context(|| format!("read {}", path.display()))?;
    let record: CustomizationRecord =
        serde_json::from_str(&body).with_context(|| format!("parse {}", path.display()))?;
    Ok(Some(record))
}

/// List all records, newest first by timestamp.
pub fn list() -> Result<Vec<CustomizationRecord>> {
    let dir = customizations_dir()?;
    if !dir.is_dir() {
        return Ok(Vec::new());
    }
    let mut records: Vec<CustomizationRecord> = Vec::new();
    for entry in std::fs::read_dir(&dir)? {
        let entry = entry?;
        let path = entry.path();
        let name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n,
            None => continue,
        };
        if !name.starts_with("cust_") || !name.ends_with(".json") {
            continue;
        }
        let body = match std::fs::read_to_string(&path) {
            Ok(b) => b,
            Err(_) => continue,
        };
        match serde_json::from_str::<CustomizationRecord>(&body) {
            Ok(record) => records.push(record),
            Err(e) => {
                crate::logging::warn(&format!(
                    "customization: skipping unparseable record {}: {}",
                    path.display(),
                    e
                ));
            }
        }
    }
    records.sort_by(|a, b| b.timestamp_unix.cmp(&a.timestamp_unix));
    Ok(records)
}

/// Remove a record by id. Returns `Ok(true)` if the file existed and was
/// removed, `Ok(false)` if there was no record with that id.
pub fn remove(id: &str) -> Result<bool> {
    let dir = customizations_dir()?;
    let path = dir.join(format!("{id}.json"));
    if !path.exists() {
        return Ok(false);
    }
    std::fs::remove_file(&path).with_context(|| format!("remove {}", path.display()))?;
    Ok(true)
}

// ---- #44: update-flow integration ----

/// Status of a customization after an update / against the current
/// repository state.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum UpdateStatus {
    /// All files still exist and at least one declared file's content
    /// hasn't drifted dramatically. Customization can likely be replayed.
    AppliesClean,

    /// One or more files referenced by the customization no longer exist
    /// in the repo. Manual review needed.
    MissingFiles { missing: Vec<String> },

    /// The version recorded against this customization predates the
    /// current jcode release. The customization itself may or may not
    /// still apply — surface a "needs review" so the user can replay
    /// validation.
    StaleVersion {
        recorded_at: String,
        current: String,
    },
}

/// Quick summary of one customization's post-update health.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomizationStatus {
    pub id: String,
    pub intent: String,
    pub status: UpdateStatus,
}

/// Scan all stored customizations and report their health relative to
/// the current repo state + jcode version. Used after `jcode update`
/// to surface customizations that may need review.
///
/// `repo_root` is the directory to resolve customization `files`
/// against (typically the result of `git rev-parse --show-toplevel`).
/// When `None`, file-existence checks are skipped (status falls back
/// to version-based heuristics).
pub fn scan_status(repo_root: Option<&Path>) -> Result<Vec<CustomizationStatus>> {
    let records = list()?;
    let current_version = next_code_build_meta::VERSION;
    let mut out = Vec::with_capacity(records.len());

    for record in records {
        let status = classify(&record, repo_root, current_version);
        out.push(CustomizationStatus {
            id: record.id,
            intent: record.intent,
            status,
        });
    }
    Ok(out)
}

fn classify(
    record: &CustomizationRecord,
    repo_root: Option<&Path>,
    current_version: &str,
) -> UpdateStatus {
    if let Some(root) = repo_root {
        let missing: Vec<String> = record
            .files
            .iter()
            .filter(|f| {
                let path = root.join(f);
                !path.exists()
            })
            .cloned()
            .collect();
        if !missing.is_empty() {
            return UpdateStatus::MissingFiles { missing };
        }
    }

    if record.version_at_record != current_version {
        return UpdateStatus::StaleVersion {
            recorded_at: record.version_at_record.clone(),
            current: current_version.to_string(),
        };
    }

    UpdateStatus::AppliesClean
}

#[cfg(test)]
mod tests {
    use super::*;

    fn with_temp_home<F: FnOnce()>(f: F) {
        let _lock = crate::storage::lock_test_env();
        let prev = std::env::var_os("JCODE_HOME");
        let temp = tempfile::TempDir::new().unwrap();
        crate::env::set_var("JCODE_HOME", temp.path());
        f();
        if let Some(p) = prev {
            crate::env::set_var("JCODE_HOME", p);
        } else {
            crate::env::remove_var("JCODE_HOME");
        }
    }

    #[test]
    fn record_then_get_round_trips() {
        with_temp_home(|| {
            let id = record(
                "fix tab handling in editor",
                vec!["src/tui/app/input.rs".to_string()],
                "diff --git a/x b/x\n--- a/x\n+++ b/x\n",
                Some("sess_test"),
            )
            .expect("record");

            assert!(id.starts_with("cust_"));

            let loaded = get(&id).expect("load").expect("present");
            assert_eq!(loaded.id, id);
            assert_eq!(loaded.intent, "fix tab handling in editor");
            assert_eq!(loaded.files, vec!["src/tui/app/input.rs"]);
            assert_eq!(loaded.session_id.as_deref(), Some("sess_test"));
            assert!(loaded.diff_hash.starts_with("sha256:"));
            assert_eq!(loaded.schema_version, SCHEMA_VERSION);
        });
    }

    #[test]
    fn get_returns_none_for_unknown_id() {
        with_temp_home(|| {
            assert!(get("cust_does_not_exist").unwrap().is_none());
        });
    }

    #[test]
    fn list_returns_records_newest_first() {
        with_temp_home(|| {
            // Record three with explicit sleep so timestamps differ.
            record("first", vec![], "d1", None).unwrap();
            std::thread::sleep(std::time::Duration::from_millis(1100));
            record("second", vec![], "d2", None).unwrap();
            std::thread::sleep(std::time::Duration::from_millis(1100));
            record("third", vec![], "d3", None).unwrap();

            let records = list().unwrap();
            assert_eq!(records.len(), 3);
            assert_eq!(records[0].intent, "third");
            assert_eq!(records[1].intent, "second");
            assert_eq!(records[2].intent, "first");
        });
    }

    #[test]
    fn remove_deletes_existing_record_and_reports_missing() {
        with_temp_home(|| {
            let id = record("temp", vec![], "diff", None).unwrap();
            assert!(remove(&id).unwrap(), "first remove returns true");
            assert!(get(&id).unwrap().is_none());
            assert!(!remove(&id).unwrap(), "second remove returns false");
        });
    }

    #[test]
    fn hash_diff_is_stable_and_includes_prefix() {
        let h1 = hash_diff("hello");
        let h2 = hash_diff("hello");
        let h3 = hash_diff("world");
        assert_eq!(h1, h2);
        assert_ne!(h1, h3);
        assert!(h1.starts_with("sha256:"));
        // 64 hex chars + "sha256:"
        assert_eq!(h1.len(), 7 + 64);
    }

    #[test]
    fn list_skips_unparseable_records_without_failing() {
        with_temp_home(|| {
            // Write a valid record + a malformed one in the dir.
            record("good", vec![], "d", None).unwrap();
            let dir = customizations_dir().unwrap();
            let bad_path = dir.join("cust_garbage.json");
            std::fs::write(&bad_path, "not valid json").unwrap();

            let records = list().expect("list still ok");
            assert_eq!(records.len(), 1);
            assert_eq!(records[0].intent, "good");
        });
    }
    // ---- #43: provenance / rationale / validation ----

    #[test]
    fn record_full_persists_self_dev_provenance() {
        with_temp_home(|| {
            let prov = Provenance::SelfDev {
                agent: "anthropic/claude-sonnet-4".to_string(),
                task_id: Some("task_abc".to_string()),
            };
            let id = record_full(
                "fix race in dispatch",
                vec!["src/provider/dispatch.rs".to_string()],
                "diff body",
                Some("sess_test"),
                Some(prov.clone()),
                Some("racing borrow on shared state".to_string()),
                Some(Validation {
                    description: "cargo test -p jcode --lib provider::dispatch".to_string(),
                    passed: true,
                    detail: Some("12 passed".to_string()),
                }),
            )
            .unwrap();

            let loaded = get(&id).unwrap().unwrap();
            assert_eq!(loaded.provenance, Some(prov));
            assert_eq!(
                loaded.rationale.as_deref(),
                Some("racing borrow on shared state")
            );
            let v = loaded.validation.unwrap();
            assert_eq!(
                v.description,
                "cargo test -p jcode --lib provider::dispatch"
            );
            assert!(v.passed);
            assert_eq!(v.detail.as_deref(), Some("12 passed"));
        });
    }

    #[test]
    fn record_legacy_v1_signature_leaves_new_fields_none() {
        with_temp_home(|| {
            let id = record(
                "v1 form",
                vec!["src/foo.rs".to_string()],
                "diff",
                Some("sess"),
            )
            .unwrap();

            let loaded = get(&id).unwrap().unwrap();
            assert!(loaded.provenance.is_none());
            assert!(loaded.rationale.is_none());
            assert!(loaded.validation.is_none());
        });
    }

    #[test]
    fn legacy_v1_records_on_disk_round_trip_after_schema_extension() {
        // Forward-compat: a v1 JSON file (no provenance/rationale/validation)
        // must still load into the v2 struct with those fields = None.
        with_temp_home(|| {
            let dir = customizations_dir().unwrap();
            std::fs::create_dir_all(&dir).unwrap();
            let id = "cust_1700000000_deadbeef0001";
            let v1_json = serde_json::json!({
                "schema_version": 1,
                "id": id,
                "timestamp_unix": 1700000000,
                "timestamp_iso": "2023-11-14T22:13:20+00:00",
                "files": ["src/x.rs"],
                "diff_hash": "sha256:deadbeef",
                "intent": "legacy entry",
                "version_at_record": "v0.5.0",
                "git_hash_at_record": "abcd1234"
            });
            std::fs::write(
                dir.join(format!("{id}.json")),
                serde_json::to_string_pretty(&v1_json).unwrap(),
            )
            .unwrap();

            let loaded = get(id).unwrap().unwrap();
            assert_eq!(loaded.id, id);
            assert_eq!(loaded.intent, "legacy entry");
            assert!(loaded.provenance.is_none());
            assert!(loaded.rationale.is_none());
            assert!(loaded.validation.is_none());
        });
    }

    #[test]
    fn provenance_user_serializes_with_kind_tag() {
        let p = Provenance::User {
            author: Some("alice".to_string()),
        };
        let json = serde_json::to_string(&p).unwrap();
        assert!(json.contains(r#""kind":"user""#));
        assert!(json.contains(r#""author":"alice""#));
    }

    #[test]
    fn provenance_external_round_trips_via_serde() {
        let p = Provenance::External {
            source: "git apply patch.diff".to_string(),
        };
        let json = serde_json::to_string(&p).unwrap();
        let back: Provenance = serde_json::from_str(&json).unwrap();
        assert_eq!(p, back);
    }
    // ---- #44: update-flow status scanning ----

    #[test]
    fn scan_status_returns_applies_clean_when_files_exist_and_version_matches() {
        with_temp_home(|| {
            // Create a fake repo with a tracked file.
            let repo = tempfile::TempDir::new().unwrap();
            std::fs::write(repo.path().join("src/foo.rs"), "// stub\n").ok();
            std::fs::create_dir_all(repo.path().join("src")).unwrap();
            std::fs::write(repo.path().join("src/foo.rs"), "// stub\n").unwrap();

            let id = record("tweak foo", vec!["src/foo.rs".to_string()], "diff", None).unwrap();

            // Force version_at_record to match current — record() uses
            // next_code_build_meta::VERSION which IS the current version, so this
            // is automatically true. Validate the path.
            let report = scan_status(Some(repo.path())).unwrap();
            let found = report.iter().find(|s| s.id == id).unwrap();
            assert!(matches!(found.status, UpdateStatus::AppliesClean));
        });
    }

    #[test]
    fn scan_status_flags_missing_files() {
        with_temp_home(|| {
            let repo = tempfile::TempDir::new().unwrap();
            // Don't create src/missing.rs.

            let id = record(
                "edit missing",
                vec!["src/missing.rs".to_string()],
                "diff",
                None,
            )
            .unwrap();

            let report = scan_status(Some(repo.path())).unwrap();
            let found = report.iter().find(|s| s.id == id).unwrap();
            match &found.status {
                UpdateStatus::MissingFiles { missing } => {
                    assert_eq!(missing, &vec!["src/missing.rs".to_string()]);
                }
                other => panic!("expected MissingFiles, got {:?}", other),
            }
        });
    }

    #[test]
    fn scan_status_flags_stale_version_when_recorded_under_older_jcode() {
        with_temp_home(|| {
            // Write a record manually with an older version_at_record.
            let dir = customizations_dir().unwrap();
            std::fs::create_dir_all(&dir).unwrap();
            let id = "cust_1700000000_aaaa";
            let v1_json = serde_json::json!({
                "schema_version": 1,
                "id": id,
                "timestamp_unix": 1700000000,
                "timestamp_iso": "2023-11-14T22:13:20+00:00",
                "files": [],   // no files → skip MissingFiles check
                "diff_hash": "sha256:aaaa",
                "intent": "old change",
                "version_at_record": "v0.1.0-old",
                "git_hash_at_record": "abcd"
            });
            std::fs::write(
                dir.join(format!("{id}.json")),
                serde_json::to_string_pretty(&v1_json).unwrap(),
            )
            .unwrap();

            // No repo_root → skip file existence check, fall through to version.
            let report = scan_status(None).unwrap();
            let found = report.iter().find(|s| s.id == id).unwrap();
            match &found.status {
                UpdateStatus::StaleVersion {
                    recorded_at,
                    current,
                } => {
                    assert_eq!(recorded_at, "v0.1.0-old");
                    assert_eq!(current, next_code_build_meta::VERSION);
                }
                other => panic!("expected StaleVersion, got {:?}", other),
            }
        });
    }

    #[test]
    fn scan_status_returns_empty_when_no_records() {
        with_temp_home(|| {
            let report = scan_status(None).unwrap();
            assert!(report.is_empty());
        });
    }

    #[test]
    fn scan_status_handles_no_repo_root() {
        // Without a repo_root we skip file checks entirely and fall back
        // to version comparison.
        with_temp_home(|| {
            let id = record(
                "no repo root scan",
                vec!["src/foo.rs".to_string()],
                "diff",
                None,
            )
            .unwrap();
            let report = scan_status(None).unwrap();
            let found = report.iter().find(|s| s.id == id).unwrap();
            // Version matches (we just recorded it), no file checks done.
            assert!(matches!(found.status, UpdateStatus::AppliesClean));
        });
    }
}
